### ISSUE TITLE
Wrong Language

### ISSUE THREAD

**Issue by mertozylmz** [homeeondemand/react-native-mapbox-navigation#11]
Hi @rossmartin. Forgive you, I am so burdened with you.

Different languages appear in different places. Could it be possible to add language settings? Or at least can it be done in fixed English?

![IMG_3145](https://user-images.githubusercontent.com/16558196/107428841-3bc26880-6b34-11eb-903a-bc525d2f945f.PNG)

![IMG_3146](https://user-images.githubusercontent.com/16558196/107428845-3c5aff00-6b34-11eb-9a71-272a650fa9f2.PNG)

![IMG_3144](https://user-images.githubusercontent.com/16558196/107428828-37964b00-6b34-11eb-8307-3448dbd24ad0.PNG)

**Comment by rossmartin** [comment]
The SDK should be displaying the correct language that is set by the device in the OS. I and others have witnessed that this is not the case. I think this is related to https://github.com/mapbox/mapbox-navigation-ios/issues/2605#issue-693268777

I am considering adding a language prop and setting it on the native side in ios/android. I'm not sure that will fix the issue though because the underlying problem could be in the SDK.

**Comment by mertozylmz** [comment]
Thank you man, I will try :)

**Comment by ghadeeraqraa1992** [comment]
I tried the workaround solution , but it is not working with me.
Any help ?
