### ISSUE TITLE
v2 SDK

### ISSUE THREAD

**Issue by ben-hudson** [homeeondemand/react-native-mapbox-navigation#82]
Hello,

I'm the CTO and co-founder of [Blaise Transit](https://www.blaisetransit.com/). We forked this project a while ago and have added a bunch of features to our fork.

Since the v1 SDK will be deprecated soon, I was wondering if you would like to collaborate on migrating this project to the v2 SDK. If so, drop me an email at ben@blaisetransit.com.

Looking forward to hearing from you!

**Comment by gciluffo** [comment]
Hi @ben-hudson, we recently did the work to upgrade to v2  You can reference this comment for getting the latest changes.
https://github.com/homeeondemand/react-native-mapbox-navigation/pull/66#issuecomment-1032748538

Since we inherited this project from the previous devs we are still trying to get access to the npm org to publish this. We currently have a help ticket out to npm to get access. We might just end up creating a different npm scope to publish this under if that doesnt pan out.

Just FYI I would like to be able to contribute to this more but our team has a lot of other priorities currently. Would be interested in seeing what enhancement you included in your fork.

**Comment by ben-hudson** [comment]
Thanks! We've made a fork on github (https://github.com/blaisetransit/react-native-mapbox-navigation) and looking forward to contributing

**Comment by roberto497** [comment]
I adapted the code to work with version 0.71.3 of react native, anyone interested let me know

**Comment by de1mat** [comment]
> I adapted the code to work with version 0.71.3 of react native, anyone interested let me know

I am interested...

**Comment by roberto497** [comment]
> > I adapted the code to work with version 0.71.3 of react native, anyone interested let me know
> 
> I am interested...

https://github.com/roberto497/react-native-mapbox-navigation
